### ISSUE TITLE
assets URL

### ISSUE THREAD

**Issue by Xirdion** [heimrichhannot/contao-multifileupload-bundle#2]
The bundle uses some assets like `dropzone.js`
But the path to the files is not correct. Instead of using `system/modules/multifileupload/assets` it should be `bundles/heimrichhannotcontaomultifileupload`.

**Comment by koertho** [comment]
Hi, is the error still present? I couldn't find a system path. Please also always provide Contao and Bundle version.

**Comment by rorych** [comment]
The Problem seems to still be present. 
But the paths i see are different.

In the Backend, this path is called:
/assets/dropzone-latest/dist/dropzone.js

but the js is here:
/assets/dropzone/js/dropzone.js

**Comment by fatcrobat** [comment]
Hey there, `/assets/dropzone-latest/dist/dropzone.js` is the right path. We use the latest dropzone versions shipped with our `heimrichhannot-contao-components/dropzone-latest` component. The dependency in `composer.json` is present so ensure that you install the extension using composer in order to have the `/assets/dropzone-latest/` folder installed properly.
