### ISSUE TITLE
Issues with Haste Forms

### ISSUE THREAD

**Issue by cmartin6** [heimrichhannot/contao-multifileupload-bundle#34]
**Context**
Contao version: 4.9.20
Bundle version: 1.5.0
PHP version: 7.4

**Description**
I am using this bundle in combination with codefog/contao-haste (https://github.com/codefog/contao-haste/blob/master/docs/Form/Form.md). It looks great and seems to work, the files dragged into the dropzone get uploaded to files/tmp but after form submit they keep staying there - they should be moved to the path given in the DCA (uploadFolder) instead...

**Comment by koertho** [comment]
Hi. This bundle only support Formhybrid as frontend form framework and is hardly tied to dca and dc on some code parts. There are also problems with form generator. That's not good and I would like to change it, but we don't need it in our dev setup and so such changes have a very low priority (and the todo list is veeeery long). 
The only thing I can propose is that you search for the problem and create a PR that fixes it. Than I think someone can look into it. Otherwise I assume the issue will be open very long. Sorry :disappointed:

**Comment by koertho** [comment]
@cmartin6 We added form generator support in version 1.7. Maybe it now works with haste forms.
